### PR TITLE
MSFT_xDSCWebService: Fixes issue with Certificates with Certificate Template Information

### LINKED ISSUE #606: MSFT_xDSCWebService: Issue with matching certificate when it contains Certificate Template Information
#### Details of the scenario you tried and the problem that is occurring
When a certificate for the xDSCWebService contains a Certificate Template Information OID it may fail to match the supplied certificate template name when the resource is configured to use a CertificateSubject and Certificate Template Name.

It fails because the formatted template name contains the Template Description Name and not the Template Name. These may be the same or different which is why this will work sometimes but not all the time.
It can be bypassed by supplying the template description name in CertificateTemplateName. 
Requesting the certificate would be done with the template name though.

#### Suggested solution to the issue
I fixed the same issue with the CertificateDsc resource.

#### The operating system the target node is running
I produced this on Server 2016. 

#### Version and build of PowerShell the target node is running
5.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
8.5.0.0

### PR DESCRIPTION
**Pull request by rcarpenter79**
…translate the Certificate Description Name to the Certificate Name.

#### Pull Request (PR) description
Added functions to translate the Certificate Description Name found in a Certificate Template Information OID to the Certificate Name of the template.
This makes the name consistent with the template name found when the certificate contains a Certificate Template Name OID instead.

#### This Pull Request (PR) fixes the following issues
Fixes #606 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in
      CHANGELOG.md. Entry should say what was changed, and how that affects
      users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as
      appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See
      [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See
      [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to
      [DSC Resource Style Guidelines and Best Practices](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/607)

### CODE REVIEW

**Comment by mhendric** [comment]
Hi @rcarpenter79 , thanks for the contribution! Looks like you did a lot of work here! I wanted to see if you think this would be testable in the Integration tests too, and if so, if you could add relevant tests there as well? Thanks.

**Comment by rcarpenter79** [comment]
Hi @mhendric 
Thanks.
I cheated with this submission as I fixed the same type of problem in the CertificateDsc resource.
Most of this fix was copying the functions and tests across.
I haven't looked in to any of the integration tests for DSC.
I don't mind having a look but I don't know when I will have the time to do it.

**Comment by mhendric** [comment]
Hi @rcarpenter79 , I don't want to hold off your PR too long, but I do think it's important to get Integration tests in for this as well. I'd say worst case, just open an Issue saying we need Integration tests for this scenario, we can check this one as is (after requested changes), and then work on the Integration tests later. That being said, I wouldn't mind seeing output from a manual Integration test run (i.e. execute a DSC configuration that touches this new code). Would you be able to provide that? Thanks.

**Comment by tmeckel** [comment]
If I interpret the changes correctly the code will not work on computers which are NOT joined to a domain. If this is true this will introduce a new limitation for a Pull Server because up to now you can deploy Pull Servers on arbitrary computers including those which are NOT joined to a domain.

**Comment by rcarpenter79** [comment]
That's a good point.

I don't think my code will stop the pull server being standalone. I added the subject + template to cover the scenario when the certificate is requested at runtime from a CA.

If the pull server was standalone wouldn't the certificate be pre-existing and the thumbprint known?

I suppose there could be a case where the certificate was requested from a CA but the pull server was not in the domain. I could look to add optional domain credentials to access AD.

I've had a look at the integration tests.
I think I understand it well enough to produce some tests.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tmeckel** [comment]
Just an additional remark about the fact that your PR relies on a Domain Joined computer. 

I checked out your PR and verified that you're calling `Test-TargetResource -> Find-CertificateThumbprintWithSubjectAndTemplateName -> Get-CertificateTemplatesFromActiveDirectory -> Get-DomainNamingContext` which leads to this exception on a computer which isn't joined to a domain.

```Powershell
The following exception occurred while retrieving member "Get": "The specified domain either does not exist or could
not be contacted.
"
At line:1 char:8
+ return ([System.DirectoryServices.DirectoryEntry] 'LDAP://RootDSE').G ...
+        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ExtendedTypeSystemException
    + FullyQualifiedErrorId : CatchFromBaseGetMember
```

For my personal taste the xDSCWebService resource does things it definitely should not, like configuring the firewall or doing fancy stuff with certificates, anyway. We are just agreed to deprecate and phase out the support for configuring the firewall (https://github.com/PowerShell/xPSDesiredStateConfiguration/issues/536) because for this purpose a maintained DSC resources exists and thus should be used in the DSC configuration for a Pull Server.  Aside this the code for finding and configuring an SSL certificate for a Pull Server has many issue, for example the certificate is only searched in `cert:\LocalComputer\My` (https://github.com/PowerShell/xPSDesiredStateConfiguration/issues/468#issuecomment-458108911). Perhaps we can reduce the code for configuring the SSL certificate for a Pull Server when the `CertificateDsc` DSC resource is used like we intend to proceed with the firewall stuff.

@mhendric  What's you opinion on this?

**Comment by rcarpenter79** [comment]
I agree about the firewall being a separate resource and being configured independently.

This change handles a different situation.

Ideally I would prefer to be able to get the thumbprint of a certificate that has been requested with CertificateDsc and feed that in to xDSCWebService.
This would make my change redundant and the resource code simpler.

What I’m trying to do is find that certificate after it’s been created.

The AD requirement is only needed when the certificate match contains a Certificate Template Information Oid.
When the certificate is requested the template name is used.
In the Certificate Template Information the display name is used, which may not match the name.

The AD code is only needed to find the template name from the template display name

I’m going to review the code today.
I may well be getting the template data when it isn’t needed before checking what Oid the certificate contains.
If I limit the call to only occur if a certificate has an information Oid then the resource should still work on a standalone computer.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by tmeckel** [comment]
> I agree about the firewall being a separate resource and being configured independently. This change handles a different situation. Ideally I would prefer to be able to get the thumbprint of a certificate that has been requested with CertificateDsc and feed that in to xDSCWebService. This would make my change redundant and the resource code simpler. 

From my point of view we should pursue this solution and phase out the settings  `-CertificateTemplateName` and `-CertificateSubject` just like we agreed upon to proceed with the firewall support.

Tagging @PlagueHO and @johlju for their opinions.

**Comment by rcarpenter79** [comment]
This would only allow the use of pre-generated certificates.

What would be the point of being able to create certificates with Dsc if there was then no way of using them because the thumbprint would not be known.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by rcarpenter79** [comment]
I’ve reviewed the problem you raised.
I need to make a change to the Set and Test method.
I change the method I was using in the Get method but didn’t extend it to the Set and Test.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by tmeckel** [comment]
If `CertificateDsc` is used the link should be the `FriendlyName` of a certificate. All relevant resources of `CertificateDsc` are capable of generating a friendly name for a certificate. I know a friendly name isn't unique by default but nor is the combination of `CertificateSubject`and `CertificateTemplateName`. 

I'm also aware that we don't have a parameter for the `FriendlyName` right now but to have the issue with the SSL Certficate mapping fixed in a sustainable way we should try to rely on tested and reliable code from other DSC modules. 

Oh and an ugly, dirty trick would be to allow the user to specify the `FriendlyName` inside the `CertificateThumbPrint` parameter because it is already misused because you can set the value to `AllowUnencryptedTraffic`, which disables the SSL support for the Pull Server instance. The implementation inside the xDSCWebService resource would be pretty forward because you would match the passed value against the Thumbprint. If this doesn't match then against the `FriendlyName`. A simple OR operation.

Another option would be to rely on the Subject Name just as the `xWebSite` resource does in `xWebAdministration`. https://github.com/PowerShell/xWebAdministration#xwebsite

**Comment by rcarpenter79** [comment]
OK. I will cancel this PR then.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by tmeckel** [comment]
Perhaps I was to harsh in my statements. I'm sorry if it gave the impression. Before you cancel the PR I would like to have at least @mhendric  and @PlagueHO to state their opinion on this because the are the maintainer of this module.

**Comment by rcarpenter79** [comment]
OK. I have fixed the issue in you highlighted in Find-CertificateThumbprintWithSubjectAndTemplateName.
It will now only query AD if it finds a Certificate Template Information Oid.

I will consider adding Certificate Friendly Name.
This should be possible to add quite easily in to Find-CertificateThumbprintWithSubjectAndTemplateName.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by mhendric** [comment]
Just getting caught up here. I tested the most recent commit from this PR in my lab (Win 2019 w/Desktop, NOT Domain Joined) using MSFT_xDSCWebService.Integration.tests.ps1, and it worked just fine. @tmeckel , did you still have a concern here?

Regarding simplifying the code, I'm all for it, but perhaps we should approach it as a holistic effort, and with a new Issue. We could start with a review of the whole xDSCWebService resource for areas that are now covered by other DSC modules. What do you think?

**Comment by mhendric** [comment]
@rcarpenter79 , a potential addition to the Integration tests would be to add something like the following into 'MSFT_xDSCWebService.Integration.tests.ps1'\'Invoke-CommonResourceTesting' that tests the template return value:

```
    It 'Should find expected values in Get-DscConfiguration output' {
        $script:currentConfiguration.CertificateTemplateName = Should -Be $ExpectedTemplateName
    }
```

You could potentially also add some new Configs in MSFT_xDSCWebService.config.ps1 that test various Certificate Template return values. Do you think that would be doable?

**Comment by tmeckel** [comment]
> Just getting caught up here. I tested the most recent commit from this PR in my lab (Win 2019 w/Desktop, NOT Domain Joined) using MSFT_xDSCWebService.Integration.tests.ps1, and it worked just fine. @tmeckel , did you still have a concern here?
> 

If the code works now on computers which are not joined to a domain, then I don't have any concerns left.

> Regarding simplifying the code, I'm all for it, but perhaps we should approach it as a holistic effort, and with a new Issue. We could start with a review of the whole xDSCWebService resource for areas that are now covered by other DSC modules. What do you think?

Lemme cite a comment of you for one of my first PRs that I filed ... :-D https://github.com/PowerShell/xPSDesiredStateConfiguration/pull/465#issuecomment-439181864

>  It's got to be fixed at some point though, right? No better time to fix it than while you're working on it. (I'm assuming a goal is for this module is to eventually be a high quality module https://github.com/PowerShell/DscResources/blob/master/HighQualityModuleGuidelines.md, or at a minimum, to allow easier integration into PSDscResources, which is a high quality module already.)

Okay joking :-D but to be serious, we should have this refactored this juggernaut xDSCWebService quickly because for my taste it's very hard to maintain (remember how long it took to get the PR #507 out the door!) and it's by far light years away form the 'High Quality Resource Module Plan'. You change a small piece of code inside the resource and numerous unit or integration tests explode right on. From my point of view on reason for this is the fact that the resource does so many things you can outsource to other DSC resources when you combine them in a DSC configuration. 

Thus I would refer to you again 'No better time to fix it than while you're working on it.' and propose that we take the chance that we agree that upon a procedure how to clean or simplify the code of xDSCWebService. 

I made a proposal above which follows a bit the way we did for the firewall configuration and one of the first steps could be that we support the specification of the `Friendly Name` for a certificate in the `CertificateThumbPrint` parameter. 

This opens the door for people using `CertificateDsc` to request or import a certificate for a Pull Server. Further more I would prefer to have the other two arguments `CertificateSubject` and `CertificateTemplateName` marked as deprecated as we did with the Firewall stuff (including a warning) because you could use `CertificateDsc`  to handle the certificate stuff.

Finally the support for the friendly name is pretty easy to implement for @rcarpenter79. The only bad taste about this is, that we misuse the  `CertificateThumbPrint` parameter. But I think that a "holistic effort" would more or less postpone the changes to the day hell freezes over :-D If you look at the available resources for having resources changed we only can follow a more gradual path.

**Comment by mhendric** [comment]
> Lemme cite a comment of you for one of my first PRs that I filed

Haha, good reference. In fairness though, that comment was about fixing a single letter in a single line of code to meet DSC style guidelines. I wasn't talking about making a resource wide change to remove or deprecate functionality.  If @rcarpenter79 wants to take this on in this PR, I'm not opposed, but I don't think it should be required here. That may just result in this PR getting dropped altogether. I'd rather take what @rcarpenter79 has time for, and deal with this in another Issue if necessary.

And since this is a the second time recently that a suggestion to remove or deprecate functionality has come up, I think it may be better to analyze and update the resource as a whole rather than dealing with these one at a time. It's possible that there's multiple areas that need to be deprecated/removed and which have interdependent code. If that's the case, we'd probably want to address them at the same time rather than independently.

I think a dedicated Issue would better help facilitate discussions and get consensus on what should be removed/deprecated. @tmeckel , since you are passionate about this topic, would you want to volunteer to open an Issue, and maybe give the resource an initial review of what you think is no longer necessary?

Also, I do like the idea of doing what we did for the Firewall functionality; i.e. add a Warning saying the feature will be deprecated in the future, and add examples showing how to use an alternate Module to get the same functionality instead.

**Comment by tmeckel** [comment]
> 
> 
> > Lemme cite a comment of you for one of my first PRs that I filed
> 
> Haha, good reference. In fairness though, [...]

LOL ... Sure, but hey fairplay is something for the redcoats **:-D** But TBS: I know I definitely misused your comment. But once again.. based on your comment perhaps we could agree upon to have the ability to specify the friendly name with the `CertificateThumbPrint` parameter. Easy enough for @rcarpenter79 to do. If not I'm okay with it as well but I see a chance here to pave the way for having the xDSCWebService restructured with little effort. You and @PlagueHO are the maintainers ... your choice.

> 
> I think a dedicated Issue would better help facilitate discussions and get consensus on what should be removed/deprecated. @tmeckel , since you are passionate about this topic, would you want to volunteer to open an Issue, and maybe give the resource an initial review of what you think is no longer necessary?
> 
See what always happens when you're passionate about a thing .. you inherit work **ROFL** I'll see what I can do over the weekend. I'll try to write down the ideas that I already formulated some comments above this one about how xDSCWebService  might be restructured so that we can get rid off some additional code.

> Also, I do like the idea of doing what we did for the Firewall functionality; i.e. add a Warning saying the feature will be deprecated in the future, and add examples showing how to use an alternate Module to get the same functionality instead.

I'm almost done with the implementation for issue #536 https://github.com/tmeckel/xPSDesiredStateConfiguration/tree/issue-536 ... I still wanted to conduct some deployments in various environments. Didn't have the time though. Shall I file PR already and mark it as **WIP**? Would give you or @PlagueHO, @johlju respectively the chance to do an initial review. 

Same situation with the implementation for #463 https://github.com/tmeckel/xPSDesiredStateConfiguration/tree/issue-463.

**Comment by PlagueHO** [comment]
Yep! Will do! I'll do it tomorrow - got some spare time tomorrow to do some DSC stuff.

**Comment by tmeckel** [comment]
> 
> 
> Yep! Will do! I'll do it tomorrow - got some spare time tomorrow to do some DSC stuff.

@PlagueHO what exactly you gonna do tomorrow? :-D

**Comment by PlagueHO** [comment]
Haha I re read your comment properly. :grin:

**Comment by tmeckel** [comment]
@plagueho Perhaps my English wasn't good enough... ;-) anyway... What you think about filing two PRs of my work and marking each as WIP because I'm still working on them .. Is that something we wanna adopt here? I mean having PRs which aren't really ready for merge.

**Comment by PlagueHO** [comment]
@tmeckel - your English is fine :grin: I'm just working on too many projects at once. Rather than filling the PR, I wonder if we can use the new GitHub Draft PR functionality and put it in Draft - which is the same as WIP, so I'm just being pedantic 😆 

I'm in favor of approaching the changes to this in an evolutionary approach. So getting this PR through without addressing the stuff around certificate lookup yet is OK. But I'd definitely be most comfortable seeing integration tests on this resource to make sure it does work without being domain joined (it has gone through manual testing I know, but future changes could end up changing function and regress this). Do we think it is possible to get integration tests for this that validate the non-domain joined scenario?

But there is one scenario that jumps out at me as being a potential problem: A certificate issued by an Enterprise CA (e.g. domain joined) that is then being used on a non-domain joined server. This cert would have the `Certificate Template Information` info in it which would cause the `Get-CertificateTemplatesFromActiveDirectory` to fire which does look like it would throw. It might be good to add a check at the start of `Get-CertificateTemplatesFromActiveDirectory` to check if in AD and if not write a warning and return null?

IMHO the certificate lookup functionality should be extended separately and could possibly just use the parameter options from ExportCertificate in CertificateDsc - that means it can also use the [Find-Certificate](https://github.com/PowerShell/CertificateDsc/blob/967ca580ab00d53addd867858933d5361eb56b86/Modules/CertificateDsc.Common/CertificateDsc.Common.psm1#L221) function to locate the cert rather than reinventing. As was mentioned it would be good to use the CertReq resource to get a cert issued and used dynamically.

**Comment by tmeckel** [comment]
> @tmeckel - your English is fine  I'm just working on too many projects at once. Rather than filling the PR, I wonder if we can use the new GitHub Draft PR functionality and put it in Draft - which is the same as WIP, so I'm just being pedantic 
> 

@mhendric, @PlagueHO I created two PRs in draft mode ;-)

**Comment by mhendric** [comment]
Hey @tmeckel , can you help refresh my memory and let me know if you submitted a PR to address what @rcarpenter79 was trying to accomplish here? Trying to figure out if we still need this PR or not.

**Comment by tmeckel** [comment]
> Hey @tmeckel , can you help refresh my memory and let me know if you submitted a PR to address what @rcarpenter79 was trying to accomplish here? Trying to figure out if we still need this PR or not.

Hi @mhendric! I filed two PRs (#614, #613) but they weren't connected to the stuff @rcarpenter79 wants to accomplish here. As you can see we had kinda discussion about this PR here including two new potential issues that @PlagueHO brought up in his comment. Including all the new issues that @PlagueHO and me opened regarding the xDSCWebService resource, it seems to me that we actually need an overhaul of the complete implementation and perhaps, taking into account the dicussion here, @rcarpenter79 abandoned his PR. Sad, if this is true.

**Pull request closed without merging**
