### PR TITLE
Make MSFT_xRemoteFile only re-download a file if it's changed remotely.

### PR DESCRIPTION
**Pull request by vtsingaras**
This also enables xRemoteFile to pick-up remote changes and re-download the file, instead of only re-downloading if it's locally modified.

This changes the default behavior to re-download the file even if not locally changed, if the Web Server sends neither Last-Modifed nor ETag.

Fixes: https://github.com/PowerShell/xPSDesiredStateConfiguration/issues/334

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/360)

### CODE REVIEW

**Comment by vtsingaras** [comment]
Hi, can anyone please comment on this Pull Request?

**Comment by ChristopherGLewis** [comment]
wouldn't something like this be easier?
https://stackoverflow.com/a/30129694/13532
this uses the HTTP 304 not modified process.

**Comment by johlju** [comment]
@vtsingaras Sorry that you have waited so long on a review. Are you able to continue the work on this PR? Happy to help you get this reviewed. Could you please rebase this PR against dev so that we get the latest changes?

**Comment by johlju** [comment]
@vtsingaras There is also a suggestion too only fetch the URI head in the issue #334. Is this PR implementing that method, or ruled that method out?

**Comment by vtsingaras** [comment]
@johlju I do a HEAD to the file URI to get ETag and/or Last-Modified. I will rebase it on dev probably by Monday.

**Comment by johlju** [comment]
Great, let me know when you are ready!

**Comment by briannipper** [comment]
Hi @vtsingaras thanks for all this great work on xRemoteFile... it seems that this is not moving forward and a college and I are very interested in helping out if there is anything we can do to assist in moving this forward.

We are both new to the community and aren't sure how best to help, but we have a work interest in this change moving forward, so do please let us know if we can be of assistance.

**Comment by johlju** [comment]
@briannipper since @vtsingaras hasn't responded, and haven't been active since May 25th, I think we can consider this as abandoned. If I hadn't commented on this now, it would have been automatically labeled as abandoned after another 6 days. Now it's gonna take 14 days until this is labeled abandoned. But, I think we can consider this as abandoned (no PR author activity for 14 days).
So if you would like, you can continue the work on this PR by opening a new PR that are based on the work in this PR.

**Comment by johlju** [comment]
@vtsingaras The tests are failing, can you look at those and make sure they are passing?

**Comment by mhendric** [comment]
@PlagueHO and @johlju , what do you think we should do with this one? I'm thinking maybe just close this one out...

**Comment by johlju** [comment]
There was talk about the need for this in the Slack channel, so we should keep it open so the community can continue working on this.

**Comment by kungfu71186** [comment]
@PlagueHO @johlju  I may be able to try it out myself, but I have a question about the cache. Why is there a cache file being stored? I feel like it over complicates the process and it's really not needed unless you are storing hashes.

**Pull request closed without merging**
