### PR TITLE
Release of version 8.5.0.0 of xPSDesiredStateConfiguration

### PR DESCRIPTION
**Pull request by kwirkykat**
Releasing version 8.5.0.0

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/456)

### CODE REVIEW

**Comment by PlagueHO** [comment]
@kwirkykat - I'll start picking up issues in xPSDesiredStateConfiguration if you like and see if I can start cleaning things up. Is it worth looking at making me a maintainer on this one?

**Comment by mhendric** [comment]
@PlagueHO and @kwirkykat , just checking to see what the plan is for this build. Are we going to merge this at some point? Or are we just skipping this one and waiting until the next release cycle? Wondering if we should keep updating this branch, or if this PR is ultimately just going to be closed in favor of opening a new one.

**Comment by PlagueHO** [comment]
That is a good question. I'm not actually sure what the process here is.

There is also another resource that was blocked in the last release.
- [DFSDsc](https://github.com/PowerShell/DFSDsc/pull/83)

Given how much work has been done since the last blocked release, I wonder if it isn't worth just dumping this release (and moving the changes back into #unreleased) and starting the release again.

**Comment by PlagueHO** [comment]
Given that we've now split out CHANGELOG.MD from README.MD I think this release must be cancelled and all reference to the release reverted.

**Pull request closed without merging**
