### PR TITLE
Add support for Auto Documentation - Fixes #677

### LINKED ISSUE #677: Add Automated Documentation Generation
Replicate the changes that were made in this PR:
https://github.com/dsccommunity/ComputerManagementDsc/pull/318

### PR DESCRIPTION
**Pull request by PlagueHO**
#### Pull Request (PR) description

This PR will add support for automatic documentation and Wiki generation.

#### This Pull Request (PR) fixes the following issues

- Fixes #677

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/728)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Hi @johlju - would you mind reviewing this when you get time? Thanks!

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 127 of 136 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/728)* status: all files reviewed, 5 unresolved discussions (waiting on @PlagueHO)

*[a discussion](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/728#-MjtS8YN0GSNdTw2LXsV:-MjtS8YN0GSNdTw2LXsW:b-hj39qb) (no related file):*
Should add a WikiSource folder, under .`/source`, then add a Home.md, like this: https://github.com/dsccommunity/FileSystemDsc/blob/main/source/WikiSource/Home.md. 

There is a placeholder in this file that will automatically update to the semantic version during build (and then published).

---
___
*[README.md, line 19 at r2](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/728#-MjtRG7gEoN5CWrotG0-:-MjtRG7gEoN5CWrotG00:b-b3tobt) ([raw file](https://github.com/dsccommunity/xpsdesiredstateconfiguration/blob/a3338310b61268d90de50c14ca5d186b7925b36f/README.md#L19)):*
> ```
> against that module
> ```

Maybe "against this module"? 
___
*[README.md, line 47 at r2](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/728#-MjtSKGTAH-M6ee14szH:-MjtSKGTAH-M6ee14szI:b33hiyo) ([raw file](https://github.com/dsccommunity/xpsdesiredstateconfiguration/blob/a3338310b61268d90de50c14ca5d186b7925b36f/README.md#L47)):*
> ```
> ## Resources
> ```

In the future: Seeing this, we should really try to add this ToC-list to the Home.md automatically based on the resource's README.md :thinking:  Then a contributor does not need to update this README.md for new resource. But non-blocking as that is a big thing to create. I have created a new issue for that in DocGenerator.
___
*[.vscode/settings.json, line 11 at r2](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/728#-MjtVEaC9BB7jhLHA2JS:-MjtVEaC9BB7jhLHA2JT:bp68cra) ([raw file](https://github.com/dsccommunity/xpsdesiredstateconfiguration/blob/a3338310b61268d90de50c14ca5d186b7925b36f/.vscode/settings.json#L11)):*
> ```
> "powershell.codeFormatting.pipelineIndentationStyle": "IncreaseIndentationAfterEveryPipeline",
> ```

I usually change this to '...FirstPipeline' otherwise we have to change all code again in all repos. I have (now) added and issue to fix this in Sampler.
___
*[source/DSCResources/DSC_xPackageResource/en-US/DSC_xPackageResource.schema.mfl, line 1 at r2](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/728#-MjtYPOA161nw7s25TAM:-MjtYPOBDCLbWK8knQOt:b-7aqm8) ([raw file](https://github.com/dsccommunity/xpsdesiredstateconfiguration/blob/a3338310b61268d90de50c14ca5d186b7925b36f/source/DSCResources/DSC_xPackageResource/en-US/DSC_xPackageResource.schema.mfl#L1)):*
> ```
> xMsiPackage
> ```

THis is not xMsiPackage, but xPackage? 
___
*[source/Examples/Resources/xDscWebService/5-xDscWebService_RegistrationWithSecurityBestPractices_Config.ps1, line 81 at r2](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/728#-MjtZj9xA-09QdzMu-it:-MjtZj9yAEHEnJR3hVPp:bgyap3c) ([raw file](https://github.com/dsccommunity/xpsdesiredstateconfiguration/blob/a3338310b61268d90de50c14ca5d186b7925b36f/source/Examples/Resources/xDscWebService/5-xDscWebService_RegistrationWithSecurityBestPractices_Config.ps1#L81)):*
> ```
> Import-DSCResource
> ```

I think this should still be `Import-DscResource` (lowercase 'sc' in 'Dsc'). Throughout.

**Comment by johlju** [comment]
@PlagueHO just minor things! Awesome work on this, I know how long it takes to do a PR like this 😄

**Review by PlagueHO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/728)* status: all files reviewed, 4 unresolved discussions (waiting on @johlju)

*[a discussion](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/728#-MjtS8YN0GSNdTw2LXsV:-MkLPIBUCDrst_3FQ1M4:b-vub62o) (no related file):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Should add a WikiSource folder, under .`/source`, then add a Home.md, like this: https://github.com/dsccommunity/FileSystemDsc/blob/main/source/WikiSource/Home.md. 

There is a placeholder in this file that will automatically update to the semantic version during build (and then published).
</blockquote></details>

Done.

Great stuff. Thanks @johlju - should be good to go.

---
___
*[README.md, line 19 at r2](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/728#-MjtRG7gEoN5CWrotG0-:-MkLPR-n8RDUFYutRlSK:b-896fix) ([raw file](https://github.com/dsccommunity/xpsdesiredstateconfiguration/blob/a3338310b61268d90de50c14ca5d186b7925b36f/README.md#L19)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> against that module
> ```

Maybe "against this module"? 
</blockquote></details>

Done.
___
*[README.md, line 47 at r2](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/728#-MjtSKGTAH-M6ee14szH:-MkLPXvm6iePAC1xIq2m:b-z65g8h) ([raw file](https://github.com/dsccommunity/xpsdesiredstateconfiguration/blob/a3338310b61268d90de50c14ca5d186b7925b36f/README.md#L47)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> ## Resources
> ```

In the future: Seeing this, we should really try to add this ToC-list to the Home.md automatically based on the resource's README.md :thinking:  Then a contributor does not need to update this README.md for new resource. But non-blocking as that is a big thing to create. I have created a new issue for that in DocGenerator.
</blockquote></details>

Awesome - great idea. That would be really handy.
___
*[.vscode/settings.json, line 11 at r2](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/728#-MjtVEaC9BB7jhLHA2JS:-MkLPsjvB5miR0eqYsP9:bs7wumb) ([raw file](https://github.com/dsccommunity/xpsdesiredstateconfiguration/blob/a3338310b61268d90de50c14ca5d186b7925b36f/.vscode/settings.json#L11)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> "powershell.codeFormatting.pipelineIndentationStyle": "IncreaseIndentationAfterEveryPipeline",
> ```

I usually change this to '...FirstPipeline' otherwise we have to change all code again in all repos. I have (now) added and issue to fix this in Sampler.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_xPackageResource/en-US/DSC_xPackageResource.schema.mfl, line 1 at r2](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/728#-MjtYPOA161nw7s25TAM:-MkLQIT_1EeUVBzuUhpg:boj1qgt) ([raw file](https://github.com/dsccommunity/xpsdesiredstateconfiguration/blob/a3338310b61268d90de50c14ca5d186b7925b36f/source/DSCResources/DSC_xPackageResource/en-US/DSC_xPackageResource.schema.mfl#L1)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> xMsiPackage
> ```

THis is not xMsiPackage, but xPackage? 
</blockquote></details>

Good catch. Done.
___
*[source/Examples/Resources/xDscWebService/5-xDscWebService_RegistrationWithSecurityBestPractices_Config.ps1, line 81 at r2](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/728#-MjtZj9xA-09QdzMu-it:-MkLQXnj3ZD9_QmewVlo:b830wqs) ([raw file](https://github.com/dsccommunity/xpsdesiredstateconfiguration/blob/a3338310b61268d90de50c14ca5d186b7925b36f/source/Examples/Resources/xDscWebService/5-xDscWebService_RegistrationWithSecurityBestPractices_Config.ps1#L81)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Import-DSCResource
> ```

I think this should still be `Import-DscResource` (lowercase 'sc' in 'Dsc'). Throughout.
</blockquote></details>

Fixed. Throughout.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 17 of 17 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/728#-:-MkSk0r86PaXjlwWMCz_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PlagueHO)

**Comment by PlagueHO** [comment]
Thanks @johlju - appreciate your time too!

**Pull request merged**
