### PR TITLE
DSC_xGroupResource: Fix for the issue #750

### PR DESCRIPTION
**Pull request by danielmiu**
#### Pull Request (PR) description
- This PR implements proposed workaround for the issue [750](https://github.com/dsccommunity/xPSDesiredStateConfiguration/issues/750)

#### This Pull Request (PR) fixes the following issues
- Fixes [#750](https://github.com/dsccommunity/xPSDesiredStateConfiguration/issues/750)
#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/751)

### CODE REVIEW

**Comment by danielmiu** [comment]
Just wanted to point out that all merits go to https://github.com/SDedik as he is the original provider of the workaround.

**Comment by PlagueHO** [comment]
Hi @danielmiu - thanks for submitting this! It looks like the CI is failing due to the pipelines not being updated to remove the old WS 2016 images. I've created an issue to get this resolved. Will try and do this later on today (it's a simple enough issue): https://github.com/dsccommunity/xPSDesiredStateConfiguration/issues/752

You'll then need to rebase onto main once it's merged. Sorry about that.

**Comment by PlagueHO** [comment]
I've created the PR to fix the pipeline: https://github.com/dsccommunity/xPSDesiredStateConfiguration/pull/753

Once merged you can rebase onto main and it should fix the CI.

**Comment by johlju** [comment]
The PR to fix CI has been merged. This PR can nbe rebased now.

**Comment by danielmiu** [comment]
Done, hope I didn't do a mess will rebasing :)

**Comment by PlagueHO** [comment]
@danielmiu, really strange: it looks like it's rebased fine, but the `azure-pipelines.yml` is compared against the old one before I made the CI fix. Did you fetch main from upstream before you rebased?

**Comment by danielmiu** [comment]
Yes, I did. Would it be cleaner if I just create a new PR? There aren’t that many changes required to fix the issue.

**Comment by PlagueHO** [comment]
Hi @danielmiu - maybe. If you're happy to?

**Pull request closed without merging**
