### PR TITLE
xGroup: Refactored Principal Resolution Functions for Enhanced Virtual Account Support

### LINKED ISSUE #350: xGroup fails with error "Server names cannot contain a space character”
This issue was recently raised and closed here https://github.com/PowerShell/xPSDesiredStateConfiguration/issues/288

This is still an issue in 6.3.0.0
Trying to add IIS APPPOOL\iHostWSAppPool user to the Administrator group.

Haven't had time to diagnose the full issue but seems to be thrown in the Get-PrincipalContext function.

Was able to get the desired result with this LocalGroupMember cmdlets:
`Script AddPoolUserToAdministratorGroup {`
            `GetScript = { @{ Result = '' } }`
            `SetScript = { Add-LocalGroupMember -Group Administrators -Member 'IIS APPPOOL\p') }`
            `TestScript = { [bool] ((Get-LocalGroupMember -Group Administrators).Name -eq ('IIS APPPOOL\p'))}` 
` }`

### LINKED ISSUE #763: xGroupResource Throws Exceptions when Using Multiple Local Virtual Account Types
### Problem description

Virtual Accounts are causing the xGroup Resource to fail when executing.

When using 'IIS APPPOOL' or 'NT Virtual Machine' you get:

> ArgumentException: Server names cannot contain a space character.

When using 'NT Service' you get:

> InvalidCastException: Unable to cast object of type 'System.Boolean' to
> type 'System.DirectoryServices.DirectoryEntry'.

When using 'NT Authority' you get:

> ArgumentException: Could not find a principal with the provided name
> NT AUTHORITY\... SERVICE. (Parameter 'NT AUTHORITY\...')

### Verbose logs

```text
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = ResourceTest,'className' =
MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer WEBDEVEXT with user sid
S-1-5-21-##########-##########-##########-#####.
VERBOSE: [WEBDEVEXT]: LCM:  [ Start  Test     ]  [[xGroup]DirectResourceAccess]
VERBOSE: [WEBDEVEXT]:                            [[xGroup]DirectResourceAccess] Invoking the function
Test-TargetResourceOnFullSKU for the group IIS_IUSRS.
VERBOSE: [WEBDEVEXT]:                            [[xGroup]DirectResourceAccess] A group with the name IIS_IUSRS exists.
VERBOSE: [WEBDEVEXT]:                            [[xGroup]DirectResourceAccess] Resolving FacadeServiceDev in the
domain RedactedDomain.
VERBOSE: [WEBDEVEXT]:                            [[xGroup]DirectResourceAccess] Resolving CustomerSvcWebDev in the
domain RedactedDomain.
VERBOSE: [WEBDEVEXT]:                            [[xGroup]DirectResourceAccess] Resolving AccountIDDev in the domain
RedactedDomain.
VERBOSE: [WEBDEVEXT]:                            [[xGroup]DirectResourceAccess] Resolving TFSBuild in the domain
RedactedDomain.
VERBOSE: [WEBDEVEXT]:                            [[xGroup]DirectResourceAccess] Resolving SeminarWebDev in the domain
RedactedDomain.
VERBOSE: [WEBDEVEXT]:                            [[xGroup]DirectResourceAccess] Resolving RedactedOrgWebDev in the domain
RedactedDomain.
VERBOSE: [WEBDEVEXT]:                            [[xGroup]DirectResourceAccess] Resolving AccountServiceDev in the
domain RedactedDomain.
WARNING: [WEBDEVEXT]:                            [[xGroup]DirectResourceAccess] The group member
WinNT://S-1-5-82-##########-##########-##########-##########-########## does not exist or cannot be resolved.
VERBOSE: [WEBDEVEXT]:                            [[xGroup]DirectResourceAccess] Resolving IIS
APPPOOL\GuidanceDevDisconnectedConsumer with domain trust.
VERBOSE: [WEBDEVEXT]: LCM:  [ End    Test     ]  [[xGroup]DirectResourceAccess] False in 8.4200 seconds.
PowerShell DSC resource DSC_xGroupResource  failed to execute Test-TargetResource functionality with error message:
Exception calling ".ctor" with "2" argument(s): "Server names cannot contain a space character."
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 8.919 seconds
```

### DSC configuration

```powershell
Configuration SERVER
{

    Import-DscResource -Name xGroup -ModuleName xPSDesiredStateConfiguration

    Node localhost {
        xGroup "SERVER_IIS_IUSERS_xGROUP" {
          GroupName = 'IIS_IUSRS'
          MembersToInclude = @('IIS APPPOOL\GuidanceDevDisconnectedConsumer')
          Ensure = 'Present'
        }
}
```

### Suggested solution

Stop overwriting all local machine scopes with the name of the computer
in Split-MemberName. Include the scope when calling Find-Principal,
then resolve the SID of the account using the NTAccount class for
specific scopes.

### Operating system the target node is running

```text
OsName               : Microsoft Windows Server 2016 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.6343.amd64fre.rs1_release.230913-1727
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```

### PowerShell version and build the target node is running

```text
Name                           Value
----                           -----
PSVersion                      5.1.14393.6343
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.6343
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### xPSDesiredStateConfiguration version

```text
Name    : xPSDesiredStateConfiguration
Version : 9.1.0
Path    : C:\Program
          Files\WindowsPowerShell\Modules\xPSDesiredStateConfiguration\9.1.0\xPSDesiredStateConfiguration.psd1
```

### PR DESCRIPTION
**Pull request by kenny-scelfo**
#### Pull Request (PR) description

- Enhanced Test-IsLocalMachine to recognize 'IIS APPPOOL' and 'NT VIRTUAL MACHINE' as local machine scopes, improving virtual account type coverage.
- Updated Split-MemberName to preserve original scope, allowing local accounts that do not use the computer name to be resolved.
- Extended Find-Principal with a new Scope parameter, enabling searches additional local machine scopes.
- Augmented Find-Principal to handle a predefined list of NT account scopes ('NT Authority', 'NT Service', 'IIS APPPOOL', 'NT Virtual Machine'), utilizing System.Security.Principal.NTAccount for SID resolution. This enhancement focuses on local virtual account identification.
- Implemented new integration tests for ConvertTo-Principal to verify local, virtual account resolution.
- Introduced Get-ScopeFromDistinguishedName to accurately parse scope from distinguished names, addressing issues with multiple domain components and escaped commas.
- Added unit tests for Get-ScopeFromDistinguishedName, ensuring functional correctness.
- Adjusted outside domain test to expect 'domain.com' instead of 'domain'.

#### This Pull Request (PR) fixes the following issues

- Fixes #763 
- Fixed #350 

#### Task list

- [X] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [X] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [X] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [X] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [X] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/xPSDesiredStateConfiguration/764)

### CODE REVIEW

**Review by PlagueHO — CHANGES_REQUESTED** [review]
Great stuff @kenny-scelfo - thanks for submitting this. Just some minor bits and will merge.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xPSDesiredStateConfiguration/764#-:-NirzJcoAGG7not--e4V:b-ga9h2v)* status: all files reviewed, 8 unresolved discussions (waiting on @kenny-scelfo)

___
*[`CHANGELOG.md` line 9 at r1](https://reviewable.io/reviews/dsccommunity/xPSDesiredStateConfiguration/764#-NirtAAND-_XCDdyLj4N:-NirtAAND-_XCDdyLj4O:b-142vb) ([raw file](https://github.com/dsccommunity/xPSDesiredStateConfiguration/blob/566d5dfa759a0614ebdacbdec9c731636ce66ad4/CHANGELOG.md#L9)):*
> ```Markdown
> 
> - xGroup
>   - Fixed a bug where the resource would fail if any of the group members were
> ```

Do these fix [xGroupResource Throws Exceptions when Using Multiple Local Virtual Account Types · Issue #763 · dsccommunity/xPSDesiredStateConfiguration (github.com)](https://github.com/dsccommunity/xPSDesiredStateConfiguration/issues/763)? If so, can we referrence the issue with `- Fixes [Issue #763](https://github.com/dsccommunity/xPSDesiredStateConfiguration/issues/763)`?
___
*[`source/DSCResources/DSC_xGroupResource/DSC_xGroupResource.psm1` line 2258 at r1](https://reviewable.io/reviews/dsccommunity/xPSDesiredStateConfiguration/764#-NiruakTEc9e1m_4yfeY:-NiruakTEc9e1m_4yfeZ:b-g42sme) ([raw file](https://github.com/dsccommunity/xPSDesiredStateConfiguration/blob/566d5dfa759a0614ebdacbdec9c731636ce66ad4/source/DSCResources/DSC_xGroupResource/DSC_xGroupResource.psm1#L2258)):*
> ```PowerShell
>     Specifies the distinguished name string from which the scope is to be extracted.
> .EXAMPLE
>     Get-ScopeFromDistinguishedName -DistinguishedName "CN=John Doe,OU=Users,DC=example,DC=com"
> ```

Can we include an example with an unescaped string shows (e.g., like in the unit tests - this helps explain why the function is implemented as a loop over the char array rather than a -split).
___
*[`source/DSCResources/DSC_xGroupResource/DSC_xGroupResource.psm1` line 2270 at r1](https://reviewable.io/reviews/dsccommunity/xPSDesiredStateConfiguration/764#-NirtrFu6RnkjZDpF_uu:-NirtrFu6RnkjZDpF_uv:b-gapr32) ([raw file](https://github.com/dsccommunity/xPSDesiredStateConfiguration/blob/566d5dfa759a0614ebdacbdec9c731636ce66ad4/source/DSCResources/DSC_xGroupResource/DSC_xGroupResource.psm1#L2270)):*
> ```PowerShell
>     $domainComponents = @()
>     $escaped = $false
>     $currentComponent = ""
> ```

Can we change to single quotes?
___
*[`source/DSCResources/DSC_xGroupResource/DSC_xGroupResource.psm1` line 2430 at r1](https://reviewable.io/reviews/dsccommunity/xPSDesiredStateConfiguration/764#-NirxgubEPoOdvDQ-_0M:-NirxgubEPoOdvDQ-_0N:b-ha3n7n) ([raw file](https://github.com/dsccommunity/xPSDesiredStateConfiguration/blob/566d5dfa759a0614ebdacbdec9c731636ce66ad4/source/DSCResources/DSC_xGroupResource/DSC_xGroupResource.psm1#L2430)):*
> ```PowerShell
> 
>         [Parameter(Mandatory = $true)]
>         [string]
> ```

Can we use `[System.String]`?
___
*[`source/DSCResources/DSC_xGroupResource/DSC_xGroupResource.psm1` line 2447 at r1](https://reviewable.io/reviews/dsccommunity/xPSDesiredStateConfiguration/764#-Nirx0bu5tsjDiIx1vwL:-Nirx0bu5tsjDiIx1vwM:b-6dv9dm) ([raw file](https://github.com/dsccommunity/xPSDesiredStateConfiguration/blob/566d5dfa759a0614ebdacbdec9c731636ce66ad4/source/DSCResources/DSC_xGroupResource/DSC_xGroupResource.psm1#L2447)):*
> ```PowerShell
>     {
>         $fullIdentityValue = "$Scope\$IdentityValue"
>         $ntAccount = New-Object System.Security.Principal.NTAccount($fullIdentityValue)
> ```

Can you add the parameter name here? e.g. `New-Object -TypeName ...`?
___
*[`source/DSCResources/DSC_xGroupResource/DSC_xGroupResource.psm1` line 2450 at r1](https://reviewable.io/reviews/dsccommunity/xPSDesiredStateConfiguration/764#-NirwzCU9A5smWW-0YFQ:-NirwzCU9A5smWW-0YFR:b-10emr9) ([raw file](https://github.com/dsccommunity/xPSDesiredStateConfiguration/blob/566d5dfa759a0614ebdacbdec9c731636ce66ad4/source/DSCResources/DSC_xGroupResource/DSC_xGroupResource.psm1#L2450)):*
> ```PowerShell
>         $sid = $ntAccount.Translate([System.Security.Principal.SecurityIdentifier]).Value
>         return [System.DirectoryServices.AccountManagement.Principal]::FindByIdentity($PrincipalContext, [System.DirectoryServices.AccountManagement.IdentityType]::Sid, $sid)
>     }
> ```

Can you add a blank line after this one?
___
*[`tests/Unit/DSC_xGroupResource.Tests.ps1` line 321 at r1](https://reviewable.io/reviews/dsccommunity/xPSDesiredStateConfiguration/764#-Niry9DDEW-M8Tzta-Se:-Niry9DDEW-M8Tzta-Sf:b11d2xa) ([raw file](https://github.com/dsccommunity/xPSDesiredStateConfiguration/blob/566d5dfa759a0614ebdacbdec9c731636ce66ad4/tests/Unit/DSC_xGroupResource.Tests.ps1#L321)):*
> ```PowerShell
> 
>             Context 'xGroupResource\Get-ScopeFromDistinguishedName' {
> ```

Nit: can you remove this blank line?
___
*[`tests/Unit/DSC_xGroupResource.Tests.ps1` line 322 at r1](https://reviewable.io/reviews/dsccommunity/xPSDesiredStateConfiguration/764#-NirywAO1H7BjZEWnq5b:-NirywAO1H7BjZEWnq5c:blyuhks) ([raw file](https://github.com/dsccommunity/xPSDesiredStateConfiguration/blob/566d5dfa759a0614ebdacbdec9c731636ce66ad4/tests/Unit/DSC_xGroupResource.Tests.ps1#L322)):*
> ```PowerShell
>             Context 'xGroupResource\Get-ScopeFromDistinguishedName' {
> 
>                 It 'when given a valid distinguished name it returns the correct domain name' {
> ```

Nit: to help make the test output more readable, can you begin each `It` description with a "Should". E.g., `Should return the correct domain name when given a valid distinguished name` - and throughout the remaining tests.

**Review by kenny-scelfo — COMMENTED** [review]
Thanks for the quick review.

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xPSDesiredStateConfiguration/764#-:-Niu8lno8GAow_OKI-4o:b-ncgzbp)* status: 2 of 5 files reviewed, 6 unresolved discussions (waiting on @PlagueHO)

___
*[`CHANGELOG.md` line 9 at r1](https://reviewable.io/reviews/dsccommunity/xPSDesiredStateConfiguration/764#-NirtAAND-_XCDdyLj4N:-Niu8X6a3mrhBMsRJXG7:b-896fix) ([raw file](https://github.com/dsccommunity/xPSDesiredStateConfiguration/blob/566d5dfa759a0614ebdacbdec9c731636ce66ad4/CHANGELOG.md#L9)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Do these fix [xGroupResource Throws Exceptions when Using Multiple Local Virtual Account Types · Issue #763 · dsccommunity/xPSDesiredStateConfiguration (github.com)](https://github.com/dsccommunity/xPSDesiredStateConfiguration/issues/763)? If so, can we referrence the issue with `- Fixes [Issue #763](https://github.com/dsccommunity/xPSDesiredStateConfiguration/issues/763)`?
</blockquote></details>

Done.
___
*[`source/DSCResources/DSC_xGroupResource/DSC_xGroupResource.psm1` line 2258 at r1](https://reviewable.io/reviews/dsccommunity/xPSDesiredStateConfiguration/764#-NiruakTEc9e1m_4yfeY:-Niu4q09-gIZpVxt9Y2v:b-896fix) ([raw file](https://github.com/dsccommunity/xPSDesiredStateConfiguration/blob/566d5dfa759a0614ebdacbdec9c731636ce66ad4/source/DSCResources/DSC_xGroupResource/DSC_xGroupResource.psm1#L2258)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can we include an example with an unescaped string shows (e.g., like in the unit tests - this helps explain why the function is implemented as a loop over the char array rather than a -split).
</blockquote></details>

Done.
___
*[`source/DSCResources/DSC_xGroupResource/DSC_xGroupResource.psm1` line 2270 at r1](https://reviewable.io/reviews/dsccommunity/xPSDesiredStateConfiguration/764#-NirtrFu6RnkjZDpF_uu:-Niu4iKw1rnn_Q5_Ul0I:b-896fix) ([raw file](https://github.com/dsccommunity/xPSDesiredStateConfiguration/blob/566d5dfa759a0614ebdacbdec9c731636ce66ad4/source/DSCResources/DSC_xGroupResource/DSC_xGroupResource.psm1#L2270)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can we change to single quotes?
</blockquote></details>

Done.
___
*[`source/DSCResources/DSC_xGroupResource/DSC_xGroupResource.psm1` line 2430 at r1](https://reviewable.io/reviews/dsccommunity/xPSDesiredStateConfiguration/764#-NirxgubEPoOdvDQ-_0M:-Niu4e6j68LRjKKssjNI:b-896fix) ([raw file](https://github.com/dsccommunity/xPSDesiredStateConfiguration/blob/566d5dfa759a0614ebdacbdec9c731636ce66ad4/source/DSCResources/DSC_xGroupResource/DSC_xGroupResource.psm1#L2430)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can we use `[System.String]`?
</blockquote></details>

Done.
___
*[`source/DSCResources/DSC_xGroupResource/DSC_xGroupResource.psm1` line 2447 at r1](https://reviewable.io/reviews/dsccommunity/xPSDesiredStateConfiguration/764#-Nirx0bu5tsjDiIx1vwL:-Niu69145b7EV2qlhfrc:b-896fix) ([raw file](https://github.com/dsccommunity/xPSDesiredStateConfiguration/blob/566d5dfa759a0614ebdacbdec9c731636ce66ad4/source/DSCResources/DSC_xGroupResource/DSC_xGroupResource.psm1#L2447)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you add the parameter name here? e.g. `New-Object -TypeName ...`?
</blockquote></details>

Done.
___
*[`source/DSCResources/DSC_xGroupResource/DSC_xGroupResource.psm1` line 2450 at r1](https://reviewable.io/reviews/dsccommunity/xPSDesiredStateConfiguration/764#-NirwzCU9A5smWW-0YFQ:-Niu6tw-8_kF18Fg51r7:b-896fix) ([raw file](https://github.com/dsccommunity/xPSDesiredStateConfiguration/blob/566d5dfa759a0614ebdacbdec9c731636ce66ad4/source/DSCResources/DSC_xGroupResource/DSC_xGroupResource.psm1#L2450)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you add a blank line after this one?
</blockquote></details>

Done.

**Comment by kenny-scelfo** [comment]
Looks like this also fixes #350

**Review by PlagueHO — APPROVED** [review]
Wow - yes, it does! From 2017. I have updated the PR description to close this issue as well. Thanks for all the work!

:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xPSDesiredStateConfiguration/764#-:-NiwqKBcE5bFNtotUPmf:b-2ubg64)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kenny-scelfo)

**Review by kenny-scelfo — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xPSDesiredStateConfiguration/764#-:-NkqqxJc2hopVV5Xx2cL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
