### PR TITLE
Update build files

### PR DESCRIPTION
**Pull request by dan-hughes**
#### Pull Request (PR) description

Update build files to allow Azure DevOps to build and create a release.

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/xPSDesiredStateConfiguration/770)

### CODE REVIEW

**Comment by dan-hughes** [comment]
@johlju, whenever this finishes building, there was a request to release on Discord. 

It looks like this module could do with some attention too!

**Comment by johlju** [comment]
Yes, there are probably a lot of modules left that need to be updated. 🙂

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xPSDesiredStateConfiguration/770#-:-O9EkTgl7P8SnQMffYvh:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-hughes)

**Comment by johlju** [comment]
Tried to push a new tag but it does not start the build. I tried to start it manually from AzDO but it did not recognize the tag. It must be a problem between GitHub and AzDo at the moment. Will try later.

**Comment by dan-hughes** [comment]
> Yes, there are probably a lot of modules left that need to be updated. 🙂

It might be worth starting a list of modules needing updates and see if anyone else can assist.

**Comment by johlju** [comment]
My bad, my local repo had a bunch of old tags that I mistakenly pushed. Clean that up and pushed that tag again, release running now. 🙂

**Comment by Daymarvi** [comment]
Thanks for this everyone ! really appreciate

**Pull request merged**
