### PR TITLE
xGroup: Ensure group members are always returned as an array

### LINKED ISSUE #353: xGroup: Get-DscConfiguration fails
I'm working on a fairly complex DSC configuration which contains several partial configurations. One of them contains two xGroup resources.

After I publish and run the configuration (successfully), running Get-DscConfiguration fails with:
```
Get-DscConfiguration : GetConfiguration did not succeed.
At line:1 char:1
+ Get-DscConfiguration
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_DSCLocalConfigurationManager:root/Microsoft/...gurationManager) [Get
   -DscConfiguration], CimException
    + FullyQualifiedErrorId : MI RESULT 1,Get-DscConfiguration
```

DSC event log shows three error entries:
```
Job {5386BEF3-3C1A-11E7-80C3-3E1DBB675B2A} : 
Message Unable to cast object of type 'System.Management.Automation.PSObject' to type 'System.Object[]'. 
HResult -2147467262 
StackTrack    at System.Management.Automation.LanguagePrimitives.ConvertTo[T](Object valueToConvert)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.ResourceProviderAdapter.GetPSObjectArrayValue(CimType cimType, Object propertyValue)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.ResourceProviderAdapter.GetTargetResource(IntPtr resourceConfigurationInstanceHandle, IntPtr nonResourcePropetiesHandle, IntPtr metaConfigHandle, IntPtr regInstanceHandle, IStreamsHandler plugInStreamsHandler, IntPtr& outputInstanceHandle, IntPtr& errorInstanceHandle)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscPluginManagedEntryWrapper.Get(IntPtr provContext, IntPtr instance, IntPtr nonResourcePropeties, IntPtr metaConfig, IntPtr regInstance, IntPtr outputInstance, IntPtr extendedError)
```

```
Job {5386BEF3-3C1A-11E7-80C3-3E1DBB675B2A} : 
This event indicates that failure happens when LCM is processing the configuration. Error Id is 0x1. Error Detail is The SendConfigurationApply function did not succeed.. Resource Id is [xGroup]Elements_Instances and Source Info is ::48::3::xGroup. Error Message is NULL.
```

```
Job {5386BEF3-3C1A-11E7-80C3-3E1DBB675B2A} : 
MIResult: 1
Error Message: GetConfiguration did not succeed.
Message ID: MI RESULT 1
Error Category: 0
Error Code: 1
Error Type: MI
```

The error occurs when either one or both xGroup resources are present.

If I manually import MSFT_xGroupResource.psm1 in a powershell window and run Get-TargetResource, it runs fine.

I don't have a minimal example for now, but if I could get some guidance on debugging the configuration as it is now, I'd be more than happy to take a look.

OS: 
```
Windows Server 2012R2
```
$PSVersionTable:
```
Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.36366
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
xPSDesiredStateConfiguration: 
```
6.4.0.0
```

### PR DESCRIPTION
**Pull request by ralish**
#### Pull Request (PR) description

PowerShell will unpack single element arrays on function return by default. That's problematic when we explicitly expect an array. This fixes issue #353 which occurs when running `Get-DscConfiguration` where the configuration has at least one `xGroup` state for a group which contains only a single member. The fix is simply to ensure an array is always returned, even if there's <2 elements.

#### This Pull Request (PR) fixes the following issues

- Fixes #353

#### Task list
- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/701)

### CODE REVIEW

**Comment by ralish** [comment]
Anything I can do to help push this along?

**Comment by PlagueHO** [comment]
Hi @ralish - sorry about missing this. It looks like the tests are failing - can you take a look?

**Comment by ralish** [comment]
@PlagueHO Thanks, tests look good now. I've taken a different approach to fix the issue in the process of fixing them. All details in the commit message.

**Comment by ralish** [comment]
No code changes in that last (force) push; just fixing a description in the commit message.

**Comment by PlagueHO** [comment]
Thanks @ralish - once the tests pass I'll review and we'll get this through. Thanks for your work on this!

**Comment by ralish** [comment]
All looks good with tests :)

**Review by PlagueHO — CHANGES_REQUESTED** [review]
Thanks @ralish!

Is it possible to add a unit test to validate this?

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/701#-:-MNS1g_c1uaxou8GjOe7:bnpbshx)* status: all files reviewed, 2 unresolved discussions (waiting on @ralish)

___
*[source/DSCResources/DSC_xGroupResource/DSC_xGroupResource.psm1, line 390 at r1](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/701#-MNS1dMY3TRFT1wu1lVR:-MNS1dMY3TRFT1wu1lVS:b-2llg11) ([raw file](https://github.com/dsccommunity/xpsdesiredstateconfiguration/blob/239fec70c97626f903f97f45246b85c6260091ef/source/DSCResources/DSC_xGroupResource/DSC_xGroupResource.psm1#L390)):*
> ```PowerShell
>                 -Credential $Credential -Disposables $disposables
> 
>             if ($members -is [String])
> ```

Can you change to `[System.String]` (removal of type accelerator)?
___
*[source/DSCResources/DSC_xGroupResource/DSC_xGroupResource.psm1, line 465 at r1](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/701#-MNS18dMDn7U-naH6BOL:-MNS18dMDn7U-naH6BOM:b-2llg11) ([raw file](https://github.com/dsccommunity/xpsdesiredstateconfiguration/blob/239fec70c97626f903f97f45246b85c6260091ef/source/DSCResources/DSC_xGroupResource/DSC_xGroupResource.psm1#L465)):*
> ```PowerShell
>     $members = Get-MembersOnNanoServer -Group $group
> 
>     if ($members -is [String])
> ```

Can you change to `[System.String]` (removal of type accelerator)?

**Comment by ralish** [comment]
Both types changed as requested. Regarding the unit test, what did you have in mind? I'm assuming something that checks that a single element array is returned for an invocation expected to return a single group member?

**Comment by PlagueHO** [comment]
Hi @ralish - yep - just a simple test that validates that the type string array is always returned, even if a group contains a single member.

**Review by ralish — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/701)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @PlagueHO)

___
*[source/DSCResources/DSC_xGroupResource/DSC_xGroupResource.psm1, line 390 at r1](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/701#-MNS1dMY3TRFT1wu1lVR:-MNVr6w_-dVg1q3WiAGY:b-896fix) ([raw file](https://github.com/dsccommunity/xpsdesiredstateconfiguration/blob/239fec70c97626f903f97f45246b85c6260091ef/source/DSCResources/DSC_xGroupResource/DSC_xGroupResource.psm1#L390)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you change to `[System.String]` (removal of type accelerator)?
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_xGroupResource/DSC_xGroupResource.psm1, line 465 at r1](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/701#-MNS18dMDn7U-naH6BOL:-MNVr6b25crB1zXXwtFY:b-896fix) ([raw file](https://github.com/dsccommunity/xpsdesiredstateconfiguration/blob/239fec70c97626f903f97f45246b85c6260091ef/source/DSCResources/DSC_xGroupResource/DSC_xGroupResource.psm1#L465)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you change to `[System.String]` (removal of type accelerator)?
</blockquote></details>

Done.

**Comment by ralish** [comment]
@PlagueHO Have added two unit tests which should check the behaviour (one for Nano and one for full SKU). Details in the commit message.

**Review by PlagueHO — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/701)* status: all files reviewed, 2 unresolved discussions (waiting on @ralish)

___
*[tests/Unit/DSC_xGroupResource.Tests.ps1, line 387 at r3](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/701#-MNX2tZrCTMxu8pTsLWG:-MNX2tZrCTMxu8pTsLWH:b-e41y4k) ([raw file](https://github.com/dsccommunity/xpsdesiredstateconfiguration/blob/05c5a1167f1213cdcb8f895e34dd719ecd0b57f6/tests/Unit/DSC_xGroupResource.Tests.ps1#L387)):*
> ```PowerShell
>                         $getTargetResourceResult.Ensure | Should -Be 'Present'
>                         $getTargetResourceResult.Description | Should -Be $script:testGroupDescription
>                         $getTargetResourceResult.Members | Should -Be $testMembersSingle
> ```

Could you add a validation that they type of `$getTargetResourceResult.Members` is an array of strings because I think the comparison above will pass even if an array is not returned.
___
*[tests/Unit/DSC_xGroupResource.Tests.ps1, line 939 at r3](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/701#-MNX87ZC27kPhvXVYC00:-MNX87ZDBKTBgTDU6jVv:b-e41y4k) ([raw file](https://github.com/dsccommunity/xpsdesiredstateconfiguration/blob/05c5a1167f1213cdcb8f895e34dd719ecd0b57f6/tests/Unit/DSC_xGroupResource.Tests.ps1#L939)):*
> ```PowerShell
>                         $getTargetResourceResult.Ensure | Should -Be 'Present'
>                         $getTargetResourceResult.Description | Should -Be $script:testGroupDescription
>                         $getTargetResourceResult.Members | Should -Be $testMembersSingle
> ```

Could you add a validation that they type of `$getTargetResourceResult.Members` is an array of strings because I think the comparison above will pass even if an array is not returned.

**Comment by ralish** [comment]
Very good catch, I should have realised that. I've added an explicit type check to both of the single member tests that the `Members` property is of `Object[]` type. Not using `String[]` is deliberate as PowerShell arrays are not typed by default.

I've also thoroughly tested all of this on a Windows Server 2016 VM with the updated tests and confirmed it *does* correctly fail the test if the single member is returned as a string instead of as the single element of an object array.

**Review by ralish — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/701)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @PlagueHO)

___
*[tests/Unit/DSC_xGroupResource.Tests.ps1, line 387 at r3](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/701#-MNX2tZrCTMxu8pTsLWG:-MNfyX6b-POmjAoCvG58:b-896fix) ([raw file](https://github.com/dsccommunity/xpsdesiredstateconfiguration/blob/05c5a1167f1213cdcb8f895e34dd719ecd0b57f6/tests/Unit/DSC_xGroupResource.Tests.ps1#L387)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Could you add a validation that they type of `$getTargetResourceResult.Members` is an array of strings because I think the comparison above will pass even if an array is not returned.
</blockquote></details>

Done.
___
*[tests/Unit/DSC_xGroupResource.Tests.ps1, line 939 at r3](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/701#-MNX87ZC27kPhvXVYC00:-MNfyWWE30--nH_7snPF:b-896fix) ([raw file](https://github.com/dsccommunity/xpsdesiredstateconfiguration/blob/05c5a1167f1213cdcb8f895e34dd719ecd0b57f6/tests/Unit/DSC_xGroupResource.Tests.ps1#L939)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Could you add a validation that they type of `$getTargetResourceResult.Members` is an array of strings because I think the comparison above will pass even if an array is not returned.
</blockquote></details>

Done.

**Review by PlagueHO — APPROVED** [review]
Sorry @ralish - can you resolve the conflicts and I'll merge?

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/701#-:-MOK5pMUD-ZEoGjYxitk:bj60g43)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by PlagueHO — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/701#-:-MOK64vk6INSFY4kEf-2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by PlagueHO — APPROVED** [review]
Ignore me - there weren't any conflicts - just needed to update the branch. Once tests pass I'll merge.

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/701#-:-MOK664LDM_KfUlYpz_G:b-si7can)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by ralish** [comment]
@PlagueHO I think this is good to merge now? All tests looking good.

**Review by PlagueHO — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/701#-:-MOjDtYf7pv0nri0exuu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ralish)

**Pull request merged**
