### PR TITLE
Convert DSCWebService to use localized strings - Fixes #622

### LINKED ISSUE #622: xDSCWebService: Move Strings into Localization File

### PR DESCRIPTION
**Pull request by PlagueHO**
#### Pull Request (PR) description

This PR moves all the strings in DSCWebService to be localized. I also cleaned up a few style issues - but there are more to do.

#### This Pull Request (PR) fixes the following issues

- Fixes #622 

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

@johlju - would you mind reviewing when you have time?

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/697)

### CODE REVIEW

**Review by johlju — CHANGES_REQUESTED** [review]
A few comments, probably will make the HQRM test pass too. Haven't looked why the other tests failed.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/697#-:-MFy-IZ6EA9bIciL6NyY:b-7u3jpx)* status: all files reviewed, 7 unresolved discussions (waiting on @PlagueHO)

___
*[source/DSCResources/DSC_xDSCWebService/DSC_xDSCWebService.psm1, line 834 at r1](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/697#-MFxto-e5gWTTTj5Lf3J:-MFxto-e5gWTTTj5Lf3K:bwmpjjf) ([raw file](https://github.com/dsccommunity/xpsdesiredstateconfiguration/blob/3624ad80b141955a9d1ed3029bd2c2831f18beb6/source/DSCResources/DSC_xDSCWebService/DSC_xDSCWebService.psm1#L834)):*
> ```
> PullServerWebSiteDoesNotExistAndShouldNot
> ```

I think this should be `PullServerWebSitePortMismatch`
___
*[source/DSCResources/DSC_xDSCWebService/DSC_xDSCWebService.psm1, line 843 at r1](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/697#-MFxucdV6caxiQb2WXQb:-MFxucdV6caxiQb2WXQc:bb54wlu) ([raw file](https://github.com/dsccommunity/xpsdesiredstateconfiguration/blob/3624ad80b141955a9d1ed3029bd2c2831f18beb6/source/DSCResources/DSC_xDSCWebService/DSC_xDSCWebService.psm1#L843)):*
> ```
> PullServerWebSite
> ```

I think this should be `PullServerWebSiteApplicationPoolMismatch`
___
*[source/DSCResources/DSC_xDSCWebService/DSC_xDSCWebService.psm1, line 904 at r1](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/697#-MFxvItQ2i1KvgrZkuw4:-MFxvItQ2i1KvgrZkuw5:bccayrd) ([raw file](https://github.com/dsccommunity/xpsdesiredstateconfiguration/blob/3624ad80b141955a9d1ed3029bd2c2831f18beb6/source/DSCResources/DSC_xDSCWebService/DSC_xDSCWebService.psm1#L904)):*
> ```
> Write-Verbose -Message ($script:localizedData.PullServerWebSitePhysicalPathMismatch -f $EndpointName, $PhysicalPath)
> ```

This should write out actual and desired state. Currently it write out the desired state as the current path. If there is not a (easy) way to get the currect path, then just rephrase the localized string.
___
*[source/DSCResources/DSC_xDSCWebService/DSC_xDSCWebService.psm1, line 913 at r1](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/697#-MFxw3vEEwNjZrjkngIK:-MFxw3vEEwNjZrjkngIL:bjlzaut) ([raw file](https://github.com/dsccommunity/xpsdesiredstateconfiguration/blob/3624ad80b141955a9d1ed3029bd2c2831f18beb6/source/DSCResources/DSC_xDSCWebService/DSC_xDSCWebService.psm1#L913)):*
> ```
> PullServerWebSiteStateMismatch
> ```

Is this meant to be `PullServerWebSiteState`?
___
*[source/DSCResources/DSC_xDSCWebService/DSC_xDSCWebService.psm1, line 1026 at r1](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/697#-MFxwdLL0rPsJIQQ491k:-MFxwdLL0rPsJIQQ491l:b-drddhs) ([raw file](https://github.com/dsccommunity/xpsdesiredstateconfiguration/blob/3624ad80b141955a9d1ed3029bd2c2831f18beb6/source/DSCResources/DSC_xDSCWebService/DSC_xDSCWebService.psm1#L1026)):*
> ```
> Write-Verbose -Message ($script:localizedData.IisSelfSignedModuleNotInstalledButShouldBe -f $EndpointName)
> ```

DOn't think `$EndpointName` should be here, or the string is missing an `{0}`.
___
*[source/DSCResources/DSC_xDSCWebService/DSC_xDSCWebService.psm1, line 1049 at r1](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/697#-MFxy7THBAnoh1ITRzoR:-MFxy7THBAnoh1ITRzoS:b-bdkkqf) ([raw file](https://github.com/dsccommunity/xpsdesiredstateconfiguration/blob/3624ad80b141955a9d1ed3029bd2c2831f18beb6/source/DSCResources/DSC_xDSCWebService/DSC_xDSCWebService.psm1#L1049)):*
> ```
> Write-Verbose -Message ($script:localizedData.IisSelfSignedModuleNotInstalledAndShouldNotBe -f $EndpointName)
> ```

SHould not have `$EndpointName`, or the string is missing an `{0}`.
___
*[source/DSCResources/DSC_xDSCWebService/en-US/DSC_xDSCWebService.strings.psd1, line 59 at r1](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/697#-MFxxa-Z8DCdb2h5-4iS:-MFxxa-Z8DCdb2h5-4iT:b-n1lzka) ([raw file](https://github.com/dsccommunity/xpsdesiredstateconfiguration/blob/3624ad80b141955a9d1ed3029bd2c2831f18beb6/source/DSCResources/DSC_xDSCWebService/en-US/DSC_xDSCWebService.strings.psd1#L59)):*
> ```
> PullServerWebSiteModuleEnabledButShouldNotBe         = Pull Server web site '{0}' self-signed IIS module not enabled but should not be.
>     PullServerWebSiteModuleNotEnabledAndShouldNotBe      = Pull Server web site '{0}' self-signed IIS module enabled and should not be.
> ```

The strings for these two should change places I think. 'not enabled' and 'enabled' does not match the string key.

**Review by johlju — COMMENTED** [review]
Retracted some comments that was fixed in the latest commit. Still a few comments left.

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/697#-:-MFyC547CvutVHqQNXPr:bp6ke09)* status: all files reviewed, 4 unresolved discussions (waiting on @PlagueHO)

**Review by PlagueHO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/697)* status: all files reviewed, 4 unresolved discussions (waiting on @johlju)

___
*[source/DSCResources/DSC_xDSCWebService/DSC_xDSCWebService.psm1, line 904 at r1](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/697#-MFxvItQ2i1KvgrZkuw4:-MFyEOCc47L-iBkpDIb2:b-88cpw2) ([raw file](https://github.com/dsccommunity/xpsdesiredstateconfiguration/blob/3624ad80b141955a9d1ed3029bd2c2831f18beb6/source/DSCResources/DSC_xDSCWebService/DSC_xDSCWebService.psm1#L904)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Write-Verbose -Message ($script:localizedData.PullServerWebSitePhysicalPathMismatch -f $EndpointName, $PhysicalPath)
> ```

This should write out actual and desired state. Currently it write out the desired state as the current path. If there is not a (easy) way to get the currect path, then just rephrase the localized string.
</blockquote></details>

It might be best to fix this when I rewrite the whole resource. There isn't a good deal of consistency in how the module is written.
___
*[source/DSCResources/DSC_xDSCWebService/DSC_xDSCWebService.psm1, line 913 at r1](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/697#-MFxw3vEEwNjZrjkngIK:-MFyDoVn4k8JBpX3cLP3:b-r3wc0n) ([raw file](https://github.com/dsccommunity/xpsdesiredstateconfiguration/blob/3624ad80b141955a9d1ed3029bd2c2831f18beb6/source/DSCResources/DSC_xDSCWebService/DSC_xDSCWebService.psm1#L913)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> PullServerWebSiteStateMismatch
> ```

Is this meant to be `PullServerWebSiteState`?
</blockquote></details>

I think this one is correct - should be PullServerWebSiteStateMismatch
___
*[source/DSCResources/DSC_xDSCWebService/DSC_xDSCWebService.psm1, line 1026 at r1](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/697#-MFxwdLL0rPsJIQQ491k:-MFyE-etA9CRSopK3up3:b-896fix) ([raw file](https://github.com/dsccommunity/xpsdesiredstateconfiguration/blob/3624ad80b141955a9d1ed3029bd2c2831f18beb6/source/DSCResources/DSC_xDSCWebService/DSC_xDSCWebService.psm1#L1026)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Write-Verbose -Message ($script:localizedData.IisSelfSignedModuleNotInstalledButShouldBe -f $EndpointName)
> ```

DOn't think `$EndpointName` should be here, or the string is missing an `{0}`.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_xDSCWebService/DSC_xDSCWebService.psm1, line 1049 at r1](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/697#-MFxy7THBAnoh1ITRzoR:-MFyE3yYEZW-wygQZPhx:b-896fix) ([raw file](https://github.com/dsccommunity/xpsdesiredstateconfiguration/blob/3624ad80b141955a9d1ed3029bd2c2831f18beb6/source/DSCResources/DSC_xDSCWebService/DSC_xDSCWebService.psm1#L1049)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Write-Verbose -Message ($script:localizedData.IisSelfSignedModuleNotInstalledAndShouldNotBe -f $EndpointName)
> ```

SHould not have `$EndpointName`, or the string is missing an `{0}`.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_xDSCWebService/en-US/DSC_xDSCWebService.strings.psd1, line 59 at r1](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/697#-MFxxa-Z8DCdb2h5-4iS:-MFyEELrE0xzhNjA5mQ_:bws2y4c) ([raw file](https://github.com/dsccommunity/xpsdesiredstateconfiguration/blob/3624ad80b141955a9d1ed3029bd2c2831f18beb6/source/DSCResources/DSC_xDSCWebService/en-US/DSC_xDSCWebService.strings.psd1#L59)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> PullServerWebSiteModuleEnabledButShouldNotBe         = Pull Server web site '{0}' self-signed IIS module not enabled but should not be.
>     PullServerWebSiteModuleNotEnabledAndShouldNotBe      = Pull Server web site '{0}' self-signed IIS module enabled and should not be.
> ```

The strings for these two should change places I think. 'not enabled' and 'enabled' does not match the string key.
</blockquote></details>

Great catch - done.

**Review by PlagueHO — COMMENTED** [review]
Should be good to go again @johlju - thank you!

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/697#-:-MG-zfR66MUxHr5YhuOb:bi629h4)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @johlju)

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/697#-:-MG1vmHA6TiDyqEBIcjl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by johlju** [comment]
@PlagueHO great work on this one! That was a lot of strings 😄

**Comment by PlagueHO** [comment]
THank you @johlju - yes, a lot of strings! I'm going to try to slowly get through all the issues with this module to make it HQRM.

My question though: if this becomes HQRM, what do we change the name to? :)

PSDesiredStateConfigurationDsc?

**Comment by johlju** [comment]
Yeah, I think PSDesiredStateConfigurationDsc is the most intuitive. Most, if not all, resources could have moved to ComputerManagementDsc, but since some resources still need to be renamed differently to not conflict with PSDscResources maybe it is easier to just rename this module to PSDesiredStateConfigurationDsc. 

Not sure what the friendly names of the resources should be though, to not conflict with PSDscResources. Or should we rename them the same as PSDscResources. Meaning you need to use either PSDscResources or PSDesiredStateConfigurationDsc, you cannot istall both at the same time? But not sure if that works with the built-in as there was some logic added to DSC (PowerShell) to ovverride the built-in DSC resource with PSDscResources. Not sure if the override works regardless of resource module (and a resource with the same name as a built-in).

**Pull request merged**
