### PR TITLE
Fix for issue #369

### PR DESCRIPTION
**Pull request by TofuBug**
#369 

Already had to fix this for my environment we have a heavily isolated workgroup network that we are using DSC to control the configuration of those systems (Windows 10)

In this environment we have additional local admin credentials the staff that runs this little island of systems can use to make minor changes as this is a 24/7 highly critical unit

So the potential for them to muck up group membership is there, they have just enough knowledge to be dangerous

So the basic idea is that a group may still list a user that has been deleted.

The issue is that ConvertTo-Principal and Resolve-SidToPrincipal when they get a null return from System.DirectoryServices.AccountManagement.PrincipalContext 's Constructor it throws an InvalidArgumentException

Maybe I'm off in my thinking but the default behavior of that constructor is NOT to throw an exception when you attempt to retrieve a PrincipalContext that does not exists but to simply indicate as such with a return of null

I feel like the behavior of DSC resources should follow the default behavior of the systems they are managing i.e if the system we are managing does not throw an exception our DSC resource should not artificially throw an exception, I think this is a place for Write-Verbose instead 

Now obviously i think things like making sure that a group name does not contain invalid characters IS a good place for throwing Exceptions as this particular system would throw an exception independent of us using DSC to manage it

So instead of a Configuration only running until the first time it hits an Exception this allows it to run ALL the way through and actually complete the Configuration

So to facilitate this i made the following changes

- Commented out the 3 calls to New-InvalidArgumentException -ArgumentName 'Members, MembersToInclude, or MembersToExclude' -Message ($script:localizedData.CouldNotFindPrincipal -f $Sid.Value)
  - Replaced with Write-Verbose -Message ($script:localizedData.CouldNotFindPrincipal -f $Sid.Value)
- In Test-TargetResourceOnFullSKU I changed the foreach loop to go through the MembersToInclude (the provided list in the DSC Configuration) instead of the MembersToIncludeAsPrincipals generated during the Configuration running this way it can easily see if MembersToIncludeAsPrincipals do not have an item listed (Because instead of throwing an Exception when a princpal is not found we simply do not add anything to MembersToIncludeAsPrincipals) in MembersToInclude we can assume the account was not found 
  - To be honest I would rather the configuration go all the way through and just give me a verbose message it could not find the principal and let me figure out WHY instead of just stopping the configuration
  - Also the foreach loop in Test-TargetResourceOnNanoServer is already checking the MembersToInclude this way (i.e. loop through the members the configuration provides and see if anything we ACTUALLY got from querying the system is missing from that list)

I also modified the Unit tests for these changes 

- Change the test that it should throw when no principal is found to should NOT throw when no principal is found
 - Added tests to match each of these 3 unit tests that calls where no principal is found should return null.

Any questions please let me know

Ryan

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/380)

### CODE REVIEW

**Comment by johlju** [comment]
@TofuBug Sorry that someone haven't responded to this. Are you able to continue the work on this PR? Happy to help you get this reviewed. Could you please rebase this PR against dev so that we get the latest changes? Also there are a lot of files this PR changes and adds that might not have been your intention.

Also, removing that the resource throws and write a verbose message instead doesn't seem like a good approach. First this is a breaking change, secondly the problem written as a verbose message would not be seen unless running using `-Verbose`. For your scenario, would a Boolean parameter, i.e. `IgnoreMissingPrincipal`, work instead, that when set to $true changes the behavior? 

What I understand per the PR description and the issue #369 your configuration can suddenly not add a user to a group, because the user was removed? You don't have a configuration making sure that user is added back again, so the group configuration can set the desired state on next run?

**Comment by TofuBug** [comment]
@johlju 

Sorry its been a while I got swamped with projects at the office and have not even touched this. If i remember i couldn't get the AppVeyor build to work but i'm going to try and run it through right now and see if it works now.

**Comment by johlju** [comment]
We recently merged Docker support in the test framework, read about it here https://github.com/PowerShell/DscResource.Tests#run-tests-in-a-docker-windows-container maybe that can help?

**Comment by johlju** [comment]
Labeling this pull request (PR) as abandoned since it has gone 14 days or more since the last update. An abandoned PR can be continued by another contributor. The abandoned label will be removed if work on this PR is taken up again.

**Comment by mhendric** [comment]
@PlagueHO and @johlju , what do you think we should do with this one?

**Comment by PlagueHO** [comment]
This looks like it would be a great one to get in, but I'm not sure how much work is required still to do to get this in. Looks like it needs some work.

**Comment by TofuBug** [comment]
> @PlagueHO and @johlju , what do you think we should do with this one?

> This looks like it would be a great one to get in, but I'm not sure how much work is required still to do to get this in. Looks like it needs some work.

I'm sorry guys I've really been trying to get back to this one but I've been absolutely swamped with work stuff. The current state it's in was from me trying to figure out how to make AppVeyor load and test in nano server using docker (i'm still struggling with the YAML stuff) so that the code coverage would come back up into the green (That was the only thing that was failing the build. The actual unit tests themselves were passing just fine) if anyone wants to send me a good YAML file I'll try and find a few minutes this week to commit another attempt (for what it's worth I've been running my production pull server with this change implemented ever since I first committed it (mainly because I have a configuration that hits this precise issue a lot of the time) and I've yet to have any issues with this Resource.

**Comment by johlju** [comment]
Maybe the [container support](https://github.com/PowerShell/DscResource.Tests#run-integration-tests-in-order) in the test framework can help? But it expects the tests to run in the container, would it be possible? 
I have not tested using containers with the nano image, so don't know the limitation that can have.

**Comment by gaelcolas** [comment]
Removed abandoned and giving more time. Hope you'll find some time @TofuBug but no rush. I'll see if I can have a look at some point.

**Pull request closed without merging**
