### PR TITLE
[xRegistry] Set-TargetResource does not determine the type of registry value correctly

### PR DESCRIPTION
**Pull request by mkht**
#### This Pull Request (PR) fixes the following issues
#436

#### Task list

- [x] Added an entry under the Unreleased section of the change log in
      CHANGELOG.md. Entry should say what was changed, and how that affects
      users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as
      appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See
      [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See
      [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to
      [DSC Resource Style Guidelines and Best Practices](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/xpsdesiredstateconfiguration/651)

### CODE REVIEW

**Comment by mkht** [comment]
Is the check for `license/cla` working properly ?
Is there anything that I need to do ?

**Comment by PlagueHO** [comment]
Hi @mkht - CLA is no longer required. I'll turn the check off. I'm currently working on migrating this module to the new structure so that it can be released. This may mean there will be some delay in getting your change through as the overall structure has to change significantly.

**Comment by PlagueHO** [comment]
Hi @mkht - I've updated the module to the new CI process. This has changed the folder structure as well as the tests init, so you'll need to resolve the conflicts and then I'll review/merge.

**Comment by mkht** [comment]
Hi @PlagueHO 
I recreated a PR as #658
Please review ! 👍

**Pull request closed without merging**
